"""
export_utils.py - Utilities to export debate transcripts to Markdown and styled PDF.
"""

import io
from typing import List, Dict
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


def generate_markdown_transcript(topic: str, transcript: List[Dict[str, str]]) -> str:
    """Generates a cleanly formatted Markdown export of the debate transcript."""
    lines = [
        "# AI Devil's Advocate — Debate Transcript",
        "",
        f"**Topic:** {topic}",
        f"**Total Arguments/Turns:** {len(transcript)}",
        "",
        "---",
        "",
    ]

    for turn in transcript:
        speaker = turn.get("speaker", "Unknown")
        text = turn.get("text", "")
        if speaker == "Agent A":
            lines.append(f"### Agent A (Arguing FOR)\n\n{text}\n\n---")
        elif speaker == "Agent B":
            lines.append(f"### Agent B (Arguing AGAINST)\n\n{text}\n\n---")
        elif speaker == "Judge":
            lines.append(f"### Neutral Judge's Verdict\n\n{text}\n\n---")

    lines.append("\n*Generated by AI Devil's Advocate (LangGraph + Multi-Provider)*\n")
    return "\n".join(lines)


def generate_pdf_transcript(topic: str, transcript: List[Dict[str, str]]) -> bytes:
    """Generates a beautifully styled PDF document as raw bytes using ReportLab."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "DebateTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#0F172A"),
        alignment=0,
    )

    topic_style = ParagraphStyle(
        "DebateTopic",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#334155"),
        spaceAfter=12,
    )

    speaker_a_style = ParagraphStyle(
        "SpeakerA",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#1D4ED8"),
    )

    speaker_b_style = ParagraphStyle(
        "SpeakerB",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#B91C1C"),
    )

    judge_style = ParagraphStyle(
        "SpeakerJudge",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#4338CA"),
    )

    body_style = ParagraphStyle(
        "DebateBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1E293B"),
    )

    story = []

    # Title & Topic Header
    story.append(Paragraph("AI Devil's Advocate — Debate Transcript", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Topic:</b> {topic}", topic_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=14))

    for turn in transcript:
        speaker = turn.get("speaker", "Unknown")
        text = turn.get("text", "").replace("\n", "<br/>")

        if speaker == "Agent A":
            speaker_p = Paragraph("<b>Agent A (Arguing FOR)</b>", speaker_a_style)
            bg_color = colors.HexColor("#F8FAFC")
            border_color = colors.HexColor("#2563EB")
        elif speaker == "Agent B":
            speaker_p = Paragraph("<b>Agent B (Arguing AGAINST)</b>", speaker_b_style)
            bg_color = colors.HexColor("#FEF2F2")
            border_color = colors.HexColor("#DC2626")
        elif speaker == "Judge":
            speaker_p = Paragraph("<b>Neutral Judge's Verdict & Final Take</b>", judge_style)
            bg_color = colors.HexColor("#EEF2FF")
            border_color = colors.HexColor("#6366F1")
        else:
            speaker_p = Paragraph(f"<b>{speaker}</b>", styles["Heading3"])
            bg_color = colors.HexColor("#F8FAFC")
            border_color = colors.HexColor("#94A3B8")

        body_p = Paragraph(text, body_style)

        table_data = [[speaker_p], [body_p]]
        t = Table(table_data, colWidths=[530])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), bg_color),
                    ("BOX", (0, 0), (-1, -1), 1, border_color),
                    ("PADDING", (0, 0), (-1, -1), 9),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
                    ("TOPPADDING", (0, 1), (-1, 1), 4),
                ]
            )
        )

        story.append(t)
        story.append(Spacer(1, 10))

    doc.build(story)
    return buffer.getvalue()
